Add additional options for cloud armor
perfectsense/gyro-google-provider pull request #250
Opened 2023-05-22 20:29 UTC by deepanjan90

- advanced option
 - adaptive protection

2023-06-05 13:36 UTC, harjain99 commented on src/main/java/gyro/google/compute/SecurityPolicyRuleRateLimitOptionsConfig.java
> +     * The ban threshold config. Only valid when rule `action` is set to `rate_based_ban`.
```suggestion
     * The ban threshold config. Only valid when rule ``action`` is set to ``rate_based_ban``.
```

2023-06-05 13:46 UTC, harjain99 commented on src/main/java/gyro/google/compute/SecurityPolicyRuleRedirectOptionsConfig.java
> +        return null;
```suggestion
        return "";
```

2023-06-05 14:47 UTC, deepanjan90 commented on src/main/java/gyro/google/compute/SecurityPolicyRule.java
> +            (StringUtils.isBlank(getDescription()) ? "" : String.format("(%s) ", getDescription())), getPriority());
The `description` along with other fields can get updated without creating a new sub resource, but given that there can be multiple rules and no same priority can be assigned, we chose to keep the `priority` in the primary key

2023-06-05 21:41 UTC, harjain99 requested changes
The expression config doesn't seem to save the location and description and asks to update every time.

```
= Keep google::compute-security-policy security-policy-example (https://www.googleapis.com/compute/v1/projects/aerobic-lock-236714/global/securityPolicies/security-policy-example)
    ⟳ Update rule (redirect-rule-external-address-example) with priority 6
      · match:  match  → match 
        ⟳ Update match
          · expression-config:  expression-config  → expression-config 
            ⟳ Update expression-config
              · description:  '' → 'description'
              · location:  '' → '12'
```

2023-06-05 21:41 UTC, harjain99 commented on src/main/java/gyro/google/compute/SecurityPolicyRuleRateLimitOptionsConfig.java
> +    }
```suggestion
    /**
     * The key to enforce the rate limit on.
     */
    @Updatable
    @ValidStrings({ "ALL", "IP", "HTTP_HEADER", "XFF_IP", "HTTP_COOKIE", "HTTP_PATH", "SNI", "REGION_CODE" })
    public String getEnforceOnKey() {
        return enforceOnKey;
    }
```


Has the particular valid Strings:

Determines the key to enforce the rate_limit_threshold on. Possible values are:
- ALL: A single rate limit threshold is applied to all the requests matching this rule. This is the default value if "enforceOnKey" is not configured.
- IP: The source IP address of the request is the key. Each IP has this limit enforced separately.
- HTTP_HEADER: The value of the HTTP header whose name is configured under "enforceOnKeyName". The key value is truncated to the first 128 bytes of the header value. If no such header is present in the request, the key type defaults to ALL.
- XFF_IP: The first IP address (i.e. the originating client IP address) specified in the list of IPs under X-Forwarded-For HTTP header. If no such header is present or the value is not a valid IP, the key defaults to the source IP address of the request i.e. key type IP.
- HTTP_COOKIE: The value of the HTTP cookie whose name is configured under "enforceOnKeyName". The key value is truncated to the first 128 bytes of the cookie value. If no such cookie is present in the request, the key type defaults to ALL.
- HTTP_PATH: The URL path of the HTTP request. The key value is truncated to the first 128 bytes.
- SNI: Server name indication in the TLS session of the HTTPS request. The key value is truncated to the first 128 bytes. The key type defaults to ALL on a HTTP session.
- REGION_CODE: The country/region from which the request originates.
  Check the EnforceOnKey enum for the list of possible values.

2023-06-05 21:41 UTC, harjain99 commented on src/main/java/gyro/google/compute/SecurityPolicyRuleRateLimitOptionsConfig.java
> +    }
Can only be set if `enforceOnKey` is set to `HTTP_COOKIE` or `HTTP_HEADER`.

2023-06-06 14:01 UTC, harjain99 approved these changes

2023-06-06 14:48 UTC, merged